# Generated by Django 5.2.8 on 2026-03-16 01:21

import django.db.models.deletion
import isodoc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(choices=[('folder', 'Carpeta'), ('shield', 'Legal'), ('chart-bar', 'Administración'), ('code', 'Tecnología'), ('briefcase', 'Proyectos'), ('document-text', 'Procedimientos'), ('currency-dollar', 'Contabilidad'), ('office-building', 'Dirección')], default='folder', max_length=30)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('revision', 'En Revisión'), ('borrador', 'Borrador'), ('obsoleto', 'Obsoleto')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='isodoc.categoria')),
                ('grupos_acceso', models.ManyToManyField(blank=True, help_text='Vacío = todos los usuarios autenticados pueden ver', to='auth.group', verbose_name='Grupos con acceso')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('archivo', models.FileField(upload_to=isodoc.models.ruta_archivo)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('es_vigente', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='isodoc.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documentos',
                'ordering': ['-fecha_subida'],
                'unique_together': {('documento', 'version')},
            },
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('visualizacion', 'Visualización'), ('descarga', 'Descarga')], default='visualizacion', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='isodoc.versiondocumento')),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historial de Accesos',
                'ordering': ['-fecha'],
            },
        ),
    ]
